{"cells":[{"cell_type":"markdown","metadata":{},"source":["# Pythonにおけるエラー\n","*  エラーは大きく分けて以下の2つに分類される．\n",">*  構文エラー（Syntax Errors）\n",">*  例外（Exceptions） \n","*  教科書では「例外」ことを「実行時エラー」と呼んでいる．\n","*  エラーが発生すると，そのエラーに関する情報が表示される\n","*  2つのエラーで表示される内容は異なるが，主に表示されるものは以下の3つ\n",">*  エラーが発生した場所\n",">*  発生したエラーの名前\n",">*  エラーメッセージ\n"]},{"cell_type":"markdown","metadata":{},"source":["## エラーを解決できるようになるために"]},{"cell_type":"markdown","metadata":{},"source":["### エラーの原因を理解しないまま修正しない\n","* そのとき表面的に解決できたとしても，再度同様のエラーが起きた時に解決できないかもしれないし，同じエラーを何度も起こしてしまうかもしれない"]},{"cell_type":"markdown","metadata":{},"source":["### エラーメッセージをちゃんと読む\n","*  エラーメッセージの中に，何が悪いのか，どこが悪いのかといった情報が書かれている\n","*  その情報をみることで，エラーの原因を突き止めることができる\n","*  英語の意味を調べる手間を惜しまないこと\n"]},{"cell_type":"markdown","metadata":{},"source":["### エラー解決の経験を積む\n","*  多くのエラーを，試行錯誤により解決していくことで，エラー解決能力が養われる"]},{"cell_type":"markdown","metadata":{},"source":["## 構文エラー（Syntax Error）\n","*  よく目にするエラーの一つで「文法エラー」とも呼ばれているエラー\n","*  Pythonの文法に違反するコードを実行しようとしたときに発生する\n","*  Pythonインタプリタがコードを理解できず，プログラムが実行される前に検出されるエラー"]},{"cell_type":"markdown","metadata":{},"source":["### SyntaxError: incomplete input\n","*  コードの構文が不完全である場合に発生するエラー\n","*  Pythonがコードの一部を正しく理解できない場合に表示される\n","*  下のコードのように，括弧が閉じられていない場合には，Pythonがコードの終了を検出できなくなるので，このエラーが発生する  \n","*  このエラーメッセージが表示された場合，コードのどの部分が不完全であるかを調べ，適切に修正する\n","*  通常，エラーメッセージの行番号や周辺のコードが不完全な入力を示す手がかりとなる"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["my_list = [1, 2, 3"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["x = 10\n","if x < 10:"]},{"cell_type":"markdown","metadata":{},"source":["### SyntaxError: expected ':'\n","*  コードの特定の場所でコロン「`:`」が期待されているが，それが存在しない場合に発生\n","*  同様のエラーメッセージに，カンマ「`,`」が抜けているときに発生する\"SyntaxError: invalid syntax. Perhaps you forgot a comma?\"がある"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["x = 10\n","if x < 10\n","    print('1 digit')"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["my_dict = {'key1' 10, 'key2' : 20}"]},{"cell_type":"markdown","metadata":{},"source":["### SyntaxError: invalid character\n","*  Pythonが特定の文字を認識できない場合に発生する\n","*  下のコードの場合は，全角の「＝」が認識できない無効な文字となる\n","*  また，全角スペースがコード内にあると\"SyntaxError: invalid non-printable character U+3000\"というエラーメッセージが表示される"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["x ＝ 10"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["x =　10"]},{"cell_type":"markdown","metadata":{},"source":["### SyntaxError: unterminated string literal\n","\n","*  文字列リテラルが正しく閉じられていないことを示す構文エラー\n","*  シングルクォート `'` やダブルクォート `\"` で囲まれるべき文字列が，片方のクォートで閉じられていない場合に発生"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["print('Hello!)"]},{"cell_type":"markdown","metadata":{},"source":["## 例外（Exceptions）\n","*  プログラム実行中に発生するエラー\n","*  コードが正しい構文で書かれていても，実行時にエラーが発生することがる\n","*  例えば，ファイルの存在確認をせずに読み込もうとしたり，0で割り算を行おうとするなどが例外の典型\n","*  Pythonでは，例外は特定のタイプのエラーとして扱われ，発生するときにどの種類の例外が起こったかを特定することができる\n","*  例外はプログラム実行中に検知して処理することもできます（詳細は次回以降説明）"]},{"cell_type":"markdown","metadata":{},"source":["### NameError\n","\n","\n","*   組み込み関数の名前などの打ち間違いによって引き起こされるエラー\n","*   大文字と小文字を間違えているときもこのエラーになる\n","---\n","コード:    \n","```\n","pint('Hello!')\n","```\n","  \n","エラー表示:   \n","```\n","NameError                                 Traceback (most recent call last)\n","<ipython-input-3-1aaec4ef864a> in <cell line: 1>()\n","----> 1 pint('Hello!')\n","\n","NameError: name 'pint' is not defined\n","```\n","---\n","\n","\n","*  エラー表示の3行目 `----> 1 pint('Hello!')` には，エラーが発生した場所が示されている\n","*  1行目と2行目もエラーの場所に関する情報（特に気にしなくてよい）\n","*  `name 'pint' is not defined` の部分は，「`'pint'`という名前は定義されていません．」という意味"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["pint('Hello!')"]},{"cell_type":"markdown","metadata":{},"source":["### TypeError\n","*  タイプエラーは，データ型に問題があるときに表示されるエラー\n","*  関数，メソッド，演算が無効なデータ型（クラス）に対して使用された場合に発生\n","\n","---\n","\n","コード:  \n","```\n","print(10 + '円です。')\n","```\n","\n","エラー表示:  \n","```\n","TypeError                                 Traceback (most recent call last)\n","<ipython-input-4-6462738270db> in <cell line: 1>()\n","----> 1 print(10 + '円です。')\n","\n","TypeError: unsupported operand type(s) for +: 'int' and 'str'\n","```\n","---\n","  \n","*    `unsupported operand type(s) for +: 'int' and 'str'`の部分は，「+演算子は整数型（int）と文字列型（str）の演算をサポートしていません．」といったような意味になる\n","*    `print`関数のカッコ内で数値と文字列を「`+`」で連結しようとしているが，「`+`」は整数型（int）と文字列型（str）のデータを連結できないためエラーになっている  \n","\n","\n","\n"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["print(10 + '円です。')"]},{"cell_type":"markdown","metadata":{},"source":["### ValueError\n","*  対応できないデータ型が関数やメソッドに渡されたときなどに発生する\n","*  例えば，数字（0～9）以外を含む文字列を`int`関数の引数にすると，ValueErrorが発生する．\n","  \n","\n","---\n","コードの例:  \n","```\n","x = int('abc')\n","print(x)\n","```\n","  \n","エラー:  \n","```\n","ValueError                                Traceback (most recent call last)\n","<ipython-input-9-1af2b357d72b> in <cell line: 1>()\n","----> 1 x = int('abc')\n","      2 print(x)\n","\n","ValueError: invalid literal for int() with base 10: 'abc'\n","```\n","---\n","  \n","  \n","*  `base 10`は10進法を意味している\n","*  `int`関数は，10進法の整数（`base 10`）で記述された値を引数として受け取ることができる\n","*  つまり，「`invalid literal for int() with base 10: 'abc'`」は「10進法の整数（`base 10`）で記述された値（リテラル）を引数とする`int`関数に対して，10進法の整数（`base 10`）として解釈できない不正な値（リテラル）である文字列 `'abc'`を整数に変換しようとしているよ」といった意味になる"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["x = int('abc')\n","print(x)"]},{"cell_type":"markdown","metadata":{},"source":["### IndexError\n","*  リスト，タプル，文字列などに対して範囲外のインデックスを指定したときに発生する\n","*  例えば，要素が3つのリストに対してインデックス「3」を指定すると，IndexErrorが発生する．  \n","   \n","--- \n","コードの例:  \n","```\n","my_list = [2, 3, 5, 7] \n","print(my_list[4])\n","```\n","\n","エラー:  \n","```\n","IndexError                                Traceback (most recent call last)\n","<ipython-input-8-207d238f976c> in <cell line: 2>()\n","      1 my_list = [2, 3, 5, 7]\n","----> 2 print(my_list[4])\n","\n","IndexError: list index out of range\n","```\n","\n","---  \n","\n","* 「`list index out of range`」は「リストのインデックスが範囲外」といった意味になる "]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["my_list = [2, 3, 5, 7] \n","print(my_list[4])"]},{"cell_type":"markdown","metadata":{},"source":["### IndentationError\n","*  「`if 条件式:`」の次の行など，インデントが必要なところでインデントしていない場合，IndentationErrorとなる\n","*  このエラーは「インデントがあるはずでは？」という意味になる  \n","\n","コードの例:  \n","```\n","if 10 > 5:\n","print(True)\n","```\n","  \n","エラー:  \n","```\n","  File \"<ipython-input-10-95427267147a>\", line 2\n","    print(True)\n","    ^\n","IndentationError: expected an indented block after 'if' statement on line 1\n","```\n","  \n","---\n","  \n","*  「expected an indented block」は「1つのインデントされたブロックが予測されました」といった意味となる\n"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["if 10 > 5:\n","print(True)"]},{"cell_type":"markdown","metadata":{},"source":["*  インデントする必要がないところでインデントしている場合もIndentationErrorになる．  \n","  \n","---\n","コードの例:  \n","```\n","print('Hello!')\n","    print('Python')\n","```\n","\n","エラー:  \n","```\n","  File \"<ipython-input-11-0a0ea23f05b4>\", line 2\n","    print('Python')\n","    ^\n","IndentationError: unexpected indent\n","```\n","---\n","  \n","*  「unexpected indent」は「予期しないインデント」といった意味になる．  \n"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["print('Hello!')\n","    print('Python')"]},{"cell_type":"markdown","metadata":{},"source":["### KeyError\n","*  ディクショナリ（dict）を操作する際に，指定されたキーが辞書内に存在しない場合に発生するエラー\n","---\n","コードの例:  \n","```\n","my_dict = {'key1' : 10, 'key2' : 20}\n","print(my_dict['key3'])\n","```\n","\n","エラー:  \n","```\n","KeyError                                  Traceback (most recent call last)\n","<ipython-input-13-b5e5fd63cdc7> in <cell line: 2>()\n","      1 my_dict = {'key1' : 10, 'key2' : 20}\n","----> 2 print(my_dict['key3'])\n","\n","KeyError: 'key3'\n","```\n","---\n","*  このコードの場合、辞書 `my_dict` 内には '`key3`' というキーが存在しないため，'`key3`' に対する値を取得しようとしたときに KeyError が発生する  "]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["my_dict = {'key1' : 10, 'key2' : 20}\n","print(my_dict['key3'])"]},{"cell_type":"markdown","metadata":{},"source":["### ZeroDivisionError\n","* 数値を0で割ろうとしたときに発生する\n","---\n","コードの例:  \n","```\n","x = 0\n","10 / x\n","```\n","\n","エラー:  \n","```\n","ZeroDivisionError                         Traceback (most recent call last)\n","<ipython-input-14-84bb7c42511b> in <cell line: 2>()\n","      1 x = 0\n","----> 2 10 / x\n","\n","ZeroDivisionError: division by zero\n","```\n","---"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["x = 0\n","10 / x"]},{"cell_type":"markdown","metadata":{},"source":["## スタックトレース\n","*  実行時エラーが発生すると多くの場合に表示される\n","*  エラーが発生するまでの過程（関数の呼び出し順序等）が示される\n","*  エラー解決に役立つ情報\n","*  一般にスタックトレースを遡って順に問題がないか確認する\n"]},{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":["def funcA(z):\n","    ans = z * a\n","    print(ans)\n","\n","def funcB(x, y):\n","    z = x + y\n","    funcA(z)\n","\n","x = 10\n","y = 20\n","funcB(x, y)"]},{"cell_type":"markdown","metadata":{},"source":["<img src=\"./fig/08_stack_trace.png\" width=\"500\">"]},{"cell_type":"markdown","metadata":{},"source":["# 参考資料\n","*  東京大学, [5-2. モジュールの作り方](https://colab.research.google.com/github/utokyo-ipp/utokyo-ipp.github.io/blob/master/colab/5/5-2.ipynb), 「プログラミング入門」講義資料\n","*  ひらまつしょうたろう, [Python でわかる オブジェクト指向 とはなにか？【Python オブジェクト指向 の「なぜ？」を「徹底的に」解説】](https://www.udemy.com/course/oop-python/?couponCode=KEEPLEARNING), Udemy, 最終更新日 2023/7\n"]}],"metadata":{"colab":{"authorship_tag":"ABX9TyP4rf0RibbZKzyL5iY4lngz","provenance":[]},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.5"}},"nbformat":4,"nbformat_minor":0}
